### ISSUE TITLE
AttributeError

### ISSUE THREAD

**Issue by adamold** [Code-for-Miami/mia-councilmatic#43]
not sure what the problem is here, but check out 
http://162.243.115.7/legislation/161003/

> Request Method:   GET
> Request URL:    http://162.243.115.7/legislation/161003/
> Django Version: 1.8.3
> Exception Type: AttributeError
> Exception Value:  
> 'NoneType' object has no attribute 'post'
> Exception Location: /home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/councilmatic_core/models.py in current_council_seat, line 79
> Python Executable:  /home/codeformiami/Dropbox/mia-councilmatic/venv/bin/python3
> Python Version: 3.4.3
> Python Path:  
> ['/home/codeformiami/Dropbox/mia-councilmatic',
>  '/home/codeformiami/Dropbox/mia-councilmatic/venv/bin',
>  '/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4',
>  '/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/plat-x86_64-linux-gnu',
>  '/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/lib-dynload',
>  '/usr/lib/python3.4',
>  '/usr/lib/python3.4/plat-x86_64-linux-gnu',
>  '/home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages']
> Server time:    Mon, 2 May 2016 09:39:11 -0400
> Error during template rendering
> 
> In template /home/codeformiami/Dropbox/mia-councilmatic/venv/lib/python3.4/site-packages/councilmatic_core/templates/councilmatic_core/legislation.html, error at line 87
> 'NoneType' object has no attribute 'post'

**Comment by adamold** [comment]
http://162.243.115.7/legislation/150613/
More of (I think) same error. councilmatic would be pretty usable if not for these.

**Comment by ErnieAtLYD** [comment]
Found a pattern. It's being recorded by the county as the Prime Sponsor and
not the Primary Sponsor. Now big question is if this is recorded in the
scraper or the councilmatic code. Let me look.

**Comment by ErnieAtLYD** [comment]
[sigh] So these are all issues where the scraper sees the commissioner name spelled a different way - in this case, they all have middle initials when they usually do not - and they freak out because they don't know how to handle it.

So the page knows there's a sponsor, doesn't know who it's associated with, and freaks out.

Short term there needs to be a way in django to fail silently if `{{s.person.current_council_seat}}` in the `django-councilmatic` repo throws an exception.

Long term there needs to be a way to associate both someone and someone with their middle initial to be the same person.

I'll close this issue but file two different issues separately.
